Add trivy docker-cis scan
Kong/public-shared-actions pull request #1
Opened 2023-02-10 22:18 UTC by 425devon

Adds trivy docker-cis scan to Scan Docker Image shared action, tested with Scimia/shared-actions in my sandbox [HERE](https://github.com/Scimia/devons-sandbox/actions/runs/4147855003) and implemented in Scimia/shared-actions [HERE](https://github.com/Kong/shared-actions/compare/main...Scimia:shared-actions:feat/docker-cis-scanning)

2023-02-10 22:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Kong/public-shared-actions?pullRequest=1) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Kong/public-shared-actions?pullRequest=1) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Kong/public-shared-actions?pullRequest=1) it.</sub>

2023-02-10 23:15 UTC, saisatishkarra commented on security-actions/scan-docker-image/action.yml
> +        wget https://github.com/aquasecurity/trivy/releases/download/v0.37.1/trivy_0.37.1_Linux-64bit.deb
Can we make this silent and not pollute the console log with the progress?

2023-02-11 00:23 UTC, 425devon commented on security-actions/scan-docker-image/action.yml
> +        wget https://github.com/aquasecurity/trivy/releases/download/v0.37.1/trivy_0.37.1_Linux-64bit.deb
Added the flag  "-q"  to turn off Wget's output. "-nv" non-verbose is another alternative...

2023-02-11 00:33 UTC, saisatishkarra commented on security-actions/scan-docker-image/action.yml
> +        wget -q https://github.com/aquasecurity/trivy/releases/download/v0.37.1/trivy_0.37.1_Linux-64bit.deb
downloading the installer and pointing at a specific version and manually updating it everytime on breaking changes for trivy db / cache is difficult. Instead we should try using the  will help dependabot in the future to manage deps.

```
uses: docker://ghcr.io/aquasecurity/trivy:0.37.2
with:
    entrypoint: trivy
     rgs: "space separated command"
```

Also, based on https://github.com/orgs/community/discussions/25637, GitHub mounts job workspace inside the step container to share and access output files generated by the action to upload back as workflow artifacts.

2023-02-11 00:46 UTC, saisatishkarra requested changes

2023-02-11 00:46 UTC, saisatishkarra commented on security-actions/scan-docker-image/action.yml
> +        trivy image --input ${{ steps.meta.outputs.scan_image }} --compliance docker-cis -f table
Run this step after capturing the JSON file. All console log steps must be at the end of action for quick references

**Goal**: 
2nd Iteration with Table format:
Display severities in the console log honoring ignores / custom configuration (.trivyigniore in repo-root) but use either  `fail_build ` / `global_enforce_build_failure ` to set exit code for matched `global_severity_cutoff` when set.

Is this possible with two runs of trivy?

2023-02-11 00:46 UTC, saisatishkarra commented on security-actions/scan-docker-image/action.yml
> +        trivy image --input ${{ steps.meta.outputs.scan_image }} --compliance docker-cis -f json > ${{ steps.meta.outputs.cis_json_file }}
1st iteration of JSON output: Capture all severity matches from trivy including the ones ignored explicitly which allow the security team for in-depth analysis and app teams to document the reasoning for ignore and never fail based on cutoff / fail_build inputs

2023-02-11 00:46 UTC, saisatishkarra commented on security-actions/scan-docker-image/action.yml
> +    - name: upload docker-cis report
Move immediately after generating JSON output and before table format step

2023-02-11 00:47 UTC, saisatishkarra commented
cc: @vs-kong  Devon is working to integrate docker cis benchmarks action using trivy alongside the container and vulnerability scanning. Please add any inputs/thoughts.

2023-02-11 00:49 UTC, saisatishkarra commented
@425devon How does trivy manage what version `docker-cis` benchmarks are being used to evaluate the container image? Is there a way to control/manage this parameter?

2023-02-11 02:24 UTC, 425devon commented
Trivy's Docker CIS Benchmark scanning has only been released for around a week now as of v0.37.0 Currently the only CIS benchmark supported is [CIS Docker Community Edition Benchmark v1.1.0](https://aquasecurity.github.io/trivy/v0.37/docs/target/container_image/) It does look like they will support multi platform builds however I've yet to test it. Here's a decent summary of the new features: https://www.youtube.com/watch?v=3T1uXos7BXU

2023-02-14 20:52 UTC, 425devon commented on security-actions/scan-docker-image/action.yml
> +        trivy image --input ${{ steps.meta.outputs.scan_image }} --compliance docker-cis -f json > ${{ steps.meta.outputs.cis_json_file }}
✅

2023-02-14 20:53 UTC, 425devon commented on security-actions/scan-docker-image/action.yml
> +    - name: upload docker-cis report
✅

2023-02-14 20:53 UTC, 425devon commented on security-actions/scan-docker-image/action.yml
> +        trivy image --input ${{ steps.meta.outputs.scan_image }} --compliance docker-cis -f table
Addressed in latest push

2023-02-14 20:54 UTC, 425devon commented on security-actions/scan-docker-image/action.yml
> +        wget -q https://github.com/aquasecurity/trivy/releases/download/v0.37.1/trivy_0.37.1_Linux-64bit.deb
This was a great idea! Implemented.

2023-02-21 18:40 UTC, saisatishkarra commented
@425devon 
- can you update dependabot.yml to use "docker" ecosystem and point to specific action directory instead of /.
- Please resolve the conflicts

2023-02-21 21:47 UTC, saisatishkarra approved these changes
lgtm

2023-02-21 21:48 UTC, merged