feat: lualint action
Kong/public-shared-actions pull request #10
Opened 2023-03-20 06:35 UTC by pluveto

2023-03-20 06:56 UTC, dndx requested changes

2023-03-20 06:56 UTC, dndx commented on code-check-actions/lualint/README.md
> +A JSON string of the rules to use for linting. Default: `'{"max_column_width": {}, "one_line_before_else": {}, "eof_blank_line": {}, "table_ctor_comma": {}, "func_separation": {}}'`.
JSON string seems to be not super friendly, can we flatten it to actual config option for each item?

2023-03-20 06:56 UTC, dndx commented on code-check-actions/lualint/action.yml
> +    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
We can leave this as tag, we do not need to pin official actions from GitHub, only 3rd party ones.

2023-03-20 06:56 UTC, dndx commented on code-check-actions/lualint/action.yml
> +    - name: Debug inputs
We should make this conditional, maybe only prints debug log when `debug: true` is specified in the arguments.

2023-03-20 06:56 UTC, dndx commented on code-check-actions/lualint/action.yml
> +          echo "found $file";
Same, this should be removed before merging.

2023-03-20 06:56 UTC, dndx commented on code-check-actions/lualint/action.yml
> +          echo "Game over!";
This message should be changed.

2023-03-20 07:11 UTC, pluveto commented on code-check-actions/lualint/README.md
> +A JSON string of the rules to use for linting. Default: `'{"max_column_width": {}, "one_line_before_else": {}, "eof_blank_line": {}, "table_ctor_comma": {}, "func_separation": {}}'`.
Later we'll enable rule configurations. If needed we can put it into a file and load as lint rule config file.

2023-03-20 07:17 UTC, pluveto commented on code-check-actions/lualint/action.yml
> +    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
fixed.

2023-03-20 07:17 UTC, pluveto commented on code-check-actions/lualint/action.yml
> +    - name: Debug inputs
fixed.

2023-03-20 07:17 UTC, pluveto commented on code-check-actions/lualint/action.yml
> +          echo "found $file";
fixed.

2023-03-20 07:17 UTC, pluveto commented on code-check-actions/lualint/action.yml
> +          echo "Game over!";
fixed

2023-03-29 15:04 UTC, wheelerlaw submitted a review, later dismissed

2023-04-10 02:28 UTC, pluveto commented
Now line-level filter enabled

2023-04-10 13:40 UTC, wheelerlaw approved these changes

2023-04-20 12:57 UTC, saisatishkarra commented
@pluveto  When this is ready to merge, pls squash all the commits for a clean history.

2023-04-20 13:38 UTC, pluveto commented
Can we squash when merge?

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-commits

2023-04-20 14:04 UTC, saisatishkarra commented
@dndx  / @wheelerlaw  Can you review this for approval?

2023-04-20 14:05 UTC, wheelerlaw submitted a review, later dismissed

2023-04-23 07:49 UTC, dndx commented on code-check-actions/lualint/action.yml
> +        echo "[Debug] kong_gh_app_private_key: ${{ inputs.kong_gh_app_private_key }}"
This seems to be a bad idea, I suggest we remove it.

2023-04-23 07:49 UTC, dndx commented on code-check-actions/lualint/diff-line/READMD.md
> +npm install -g diff-line
Why don't we publish it, since the source code is already out in the wild inside this repo.

2023-04-23 07:55 UTC, pluveto commented on code-check-actions/lualint/action.yml
> +        echo "[Debug] kong_gh_app_private_key: ${{ inputs.kong_gh_app_private_key }}"
This won't print the key, just some stars. This is to make sure variables are set

2023-04-23 07:57 UTC, pluveto commented on code-check-actions/lualint/diff-line/READMD.md
> +npm install -g diff-line
Is this a consent?

2023-04-25 22:17 UTC, wheelerlaw submitted a review, later dismissed

2023-04-25 22:19 UTC, wheelerlaw commented on code-check-actions/lualint/action.yml
> +        echo "[Debug] kong_gh_app_private_key: ${{ inputs.kong_gh_app_private_key }}"
As long as the input comes from a secret source (which it absolutely should be), the key will not be printed—it will be masked.

2023-05-31 10:21 UTC, saisatishkarra commented on code-check-actions/lualint/diff-line/READMD.md
> +npm install -g diff-line
cc: @dndx 👀

2023-05-31 10:28 UTC, saisatishkarra commented
@dndx, pls review and approve this is ready to be merged / any other changes are needed.  I am working on another feat to integrate `[luacheck](https://github.com/lunarmodules/luacheck)` for static analysis

2024-01-12 17:20 UTC, saisatishkarra commented
closing until further need

2024-01-12 17:20 UTC, closed without merging