feat(SEC-1211): update semgrep version
Kong/public-shared-actions pull request #154
Opened 2024-09-05 06:49 UTC by pankajmouriyakong

2024-09-06 17:50 UTC, saisatishkarra requested changes

2024-09-06 17:50 UTC, saisatishkarra commented on .github/dependabot.yml
> +      include: "scope"
Add `docker` ecosystem to pull updates for any docker depdendency to `sca / scan-docker-image` directories
```
  - package-ecosystem: "docker"
    directory: "/security-actions/sca"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "docker"
      include: "scope"
  - package-ecosystem: "docker
    directory: "/security-actions/scan-docker-image"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "docker"
      include: "scope"
```

Refer to https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem for any reference

2024-09-06 21:18 UTC, pankajmouriyakong commented on .github/dependabot.yml
> +      include: "scope"
https://kongstrong.slack.com/archives/C0367E4RE9W/p1725576352196179?thread_ts=1725520302.022749&cid=C0367E4RE9W

2024-09-19 20:32 UTC, saisatishkarra approved these changes
gtm

2024-09-19 20:33 UTC, merged